version: '3.8'

services:

  
  api:
    build: ./src
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/api/
    ports:
      - 8002:8000
    env_file: .env
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./mock_data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    # expose:
    #   - 5432
    ports:
      - "5432:5432"
    env_file: .env

volumes:
  postgres_data: